import { Inter } from "next/font/google";
import "@picocss/pico"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Employee DBMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
